import type { Metadata } from "next";
import "./output.scss";
import NavBar from "./ui/NavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">   
      <body>
        <header>
          <NavBar />
        </header>
        <main>{children}</main>
        <footer></footer>
      </body>
    </html>
  );
}
